const STATUS_OK = 200;
const STATUS_CREATED = 201;
const ERROR_BAD_REQUEST = 400;
const ERROR_DEL_CARD = 403;
const ERROR_NOT_FOUND = 404;
const ERROR_SERVER = 500;

module.exports = {
  STATUS_OK,
  STATUS_CREATED,
  ERROR_SERVER,
  ERROR_BAD_REQUEST,
  ERROR_DEL_CARD,
  ERROR_NOT_FOUND,
};
